import type { LegalDocument } from './types.js';
import { CONTACT_EMAIL, LEGAL_EFFECTIVE_DATE, OPERATOR_LEGAL_NAME, SERVICE_DOMAIN, SERVICE_URL } from './operator.js';

/**
 * Terms of Service — English translation. The Polish text in `terms.pl.ts` is the
 * binding one; keep the two in lockstep, section id for section id.
 */
export const termsEn: LegalDocument = {
  id: 'terms',
  title: 'Terms of Service',
  effectiveDate: LEGAL_EFFECTIVE_DATE,
  intro:
    `Terms for the electronic services provided at ${SERVICE_DOMAIN}. By using the Service you accept the rules ` +
    'below. This is a translation — in case of any discrepancy, the Polish version prevails.',
  sections: [
    {
      id: 'uslugodawca',
      heading: '1. Provider and contact',
      blocks: [
        {
          kind: 'p',
          text:
            `The ${SERVICE_DOMAIN} service (the “Service”) is operated by ${OPERATOR_LEGAL_NAME} (the “Provider”). ` +
            `Electronic contact address for all matters: [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}).`,
        },
        {
          kind: 'p',
          text:
            'That same address is the single point of contact under Articles 11 and 12 of the Digital Services Act, ' +
            'for users and for Member State authorities alike. Contact languages are Polish and English.',
        },
      ],
    },
    {
      id: 'uslugi',
      heading: '2. Type and scope of services',
      blocks: [
        { kind: 'p', text: 'The Provider supplies the following services electronically, free of charge:' },
        {
          kind: 'ul',
          items: [
            'Game creation — you describe a game idea, an autonomous AI agent writes its code and, after review, ' +
              'publishes it in the Service.',
            'Catalog — playing games published in the Service, including games created by other users.',
            'Multiplayer — shared-screen play in which participants’ phones act as controllers.',
            'Submission tracking — a status page for your game, in-app notifications, push notifications and emails ' +
              'about progress.',
            'User account — created by signing in with a Google account.',
          ],
        },
        {
          kind: 'p',
          text:
            'The Service is currently in closed beta. Access is limited and granted at the Provider’s discretion; ' +
            'you may join a waitlist. The Provider does not guarantee that access will be granted.',
        },
      ],
    },
    {
      id: 'ai',
      heading: '3. Games are made using artificial intelligence',
      blocks: [
        {
          kind: 'p',
          text:
            'You should know this before using anything here: the games in the Service are not written by people. ' +
            'Code, graphics and sound are generated by artificial intelligence models from a description typed by a ' +
            'user. When you interact with the game creator, you are interacting with an AI system, not a human.',
        },
        {
          kind: 'p',
          text:
            'We label games in the Service as AI-generated and also embed that statement in the published game’s ' +
            'code in a machine-readable form. This implements the transparency obligation in Article 50 of ' +
            'Regulation (EU) 2024/1689 (the AI Act).',
        },
        {
          kind: 'p',
          text:
            'The practical consequence: games may contain errors, behave differently from their description, or ' +
            'never materialise at all. The Provider does not guarantee that your submission will produce a working ' +
            'game or that it will be published.',
        },
      ],
    },
    {
      id: 'wymagania',
      heading: '4. Technical requirements',
      blocks: [
        { kind: 'p', text: 'To use the Service you need:' },
        {
          kind: 'ul',
          items: [
            'a device with internet access and a current browser (Chrome, Safari, Firefox or Edge) with JavaScript ' +
              'and cookies enabled;',
            'a Google account — signing in with Google is the only way to create an account;',
            'for multiplayer — a phone with a camera to scan the QR code;',
            'for push notifications — a browser that supports them, and your consent in its prompt.',
          ],
        },
        {
          kind: 'p',
          text:
            'The Provider notes that using the internet carries standard risks (malware, interception). The Service ' +
            'is served exclusively over encrypted HTTPS, and games run in an isolated frame with no access to your ' +
            'session or data.',
        },
      ],
    },
    {
      id: 'wiek',
      heading: '5. Who may use the Service',
      blocks: [
        {
          kind: 'p',
          text:
            'The Service may be used by people aged 16 and over. By creating an account you confirm that you meet ' +
            'this condition.',
        },
        {
          kind: 'p',
          text: 'Accounts are personal. Do not share yours, and do not create an account on someone else’s behalf.',
        },
      ],
    },
    {
      id: 'zasady',
      heading: '6. Rules of use — prohibited content',
      blocks: [
        {
          kind: 'p',
          text:
            'Supplying unlawful content is prohibited. In particular, you must not submit game descriptions or ' +
            'upload material that:',
        },
        {
          kind: 'ul',
          items: [
            'breaks the law, including copyright, trade mark rights or others’ personal rights;',
            'contains pornographic content, in particular involving minors, or sexual content directed at minors;',
            'incites hatred, violence or discrimination, or promotes totalitarianism or terrorism;',
            'contains graphic violence or encourages suicide or self-harm;',
            'contains other people’s personal data, or your own contact details;',
            'attempts to manipulate the coding agent or bypass the Service’s safeguards (prompt injection), or to ' +
              'break game code out of its isolated frame.',
          ],
        },
        {
          kind: 'p',
          text:
            'Also prohibited: placing excessive load on the Service, automated use without the Provider’s consent, ' +
            'and circumventing submission quotas.',
        },
        {
          kind: 'p',
          text:
            'You are responsible for the content you supply to the Service and confirm that you hold the necessary ' +
            'rights to it.',
        },
      ],
    },
    {
      id: 'moderacja',
      heading: '7. Content moderation',
      blocks: [
        {
          kind: 'p',
          text:
            'This description implements Article 14 of the Digital Services Act — you are entitled to know how and ' +
            'when we intervene in content.',
        },
        {
          kind: 'p',
          text:
            'Every game description passes through automated moderation using an AI model before it reaches the ' +
            'coding agent. Moderation may reject a submission automatically, with no human involved. Separately, ' +
            'the Provider reviews games before publication and may decline to publish at its discretion — appearing ' +
            'in the catalog is a curatorial decision, not an automatic consequence of submitting.',
        },
        { kind: 'p', text: 'Where these Terms are breached, the Provider may, proportionately to the breach:' },
        {
          kind: 'ul',
          items: [
            'reject a submission or decline to publish a game;',
            'remove a published game from the catalog or restrict access to it;',
            'reduce submission quotas, suspend an account, or delete it in cases of gross or repeated breaches.',
          ],
        },
        {
          kind: 'p',
          text:
            'We will inform you of any such decision, stating its reason, its scope and how to appeal (a statement ' +
            'of reasons under Article 17 of the Digital Services Act). You can appeal by writing to ' +
            `[${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}); appeals are decided by a human, not an automated system.`,
        },
      ],
    },
    {
      id: 'zglaszanie',
      heading: '8. Reporting illegal content',
      blocks: [
        {
          kind: 'p',
          text:
            'If you believe a game or other content in the Service is illegal, report it. Every game carries a ' +
            `“Report game” button, and you can always write directly to [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}). ` +
            'Anyone can submit a report — no account required.',
        },
        {
          kind: 'p',
          text: 'So that a report can be acted on, it should contain (per Article 16 of the Digital Services Act):',
        },
        {
          kind: 'ul',
          items: [
            'an explanation of why you consider the content illegal;',
            'the exact location of the content — ideally the game’s URL;',
            'your name and email address (you may omit these where the report concerns offences against sexual ' +
              'freedom and decency);',
            'a statement that you believe, in good faith, that the information in the report is accurate and ' +
              'complete.',
          ],
        },
        {
          kind: 'p',
          text:
            'We confirm receipt without undue delay and inform you of our decision together with its reasons. ' +
            'Reports are handled in a timely, non-arbitrary and objective manner. A human makes the decision.',
        },
      ],
    },
    {
      id: 'prawa-autorskie',
      heading: '9. Rights to content and games',
      blocks: [
        {
          kind: 'p',
          text:
            'You keep all rights to the game description and material you submit. At the same time you grant the ' +
            'Provider a free, non-exclusive licence to reproduce, store, process (including by AI models) and make ' +
            'publicly available that material to the extent needed to build and serve the game and to run the ' +
            'Service. The licence is perpetual for published games and expires when unpublished content is deleted.',
        },
        {
          kind: 'p',
          text:
            'Game code is produced by an AI model. The copyright status of such output is unsettled under Polish ' +
            'law — a protected work must be a manifestation of human creative activity, and generated code may not ' +
            'qualify. The Provider does not resolve this question and makes no representation as to who holds ' +
            'rights in generated code.',
        },
        {
          kind: 'p',
          text:
            'Regardless of the above: to the extent the Provider holds any rights in the game code generated from ' +
            'your description, the Provider grants you a free, non-exclusive, worldwide and perpetual licence to ' +
            'use that code for any purpose, including commercially, together with the right to modify it and pass ' +
            'it on. This licence does not cover the gamedev.pl name or logo, or third-party material.',
        },
        {
          kind: 'p',
          text:
            'You may play games published in the Service for your own use. The games repository is not currently ' +
            'public; should the Provider release it under an open licence, it will announce this in the Service.',
        },
        {
          kind: 'p',
          text:
            'The gamedev.pl name and logo, and the Service’s layout and graphics, belong to the Provider and are ' +
            'not covered by the permissions above.',
        },
      ],
    },
    {
      id: 'reklamacje',
      heading: '10. Complaints',
      blocks: [
        {
          kind: 'p',
          text:
            `Complaints about the Service go to [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}). Include the email ` +
            'address linked to your account, a description of the problem, and how you would like it resolved.',
        },
        {
          kind: 'p',
          text:
            'We handle complaints within 14 days of receipt and reply to the email address given within that time. ' +
            'If we need more information, we will ask for it before that deadline expires.',
        },
      ],
    },
    {
      id: 'odpowiedzialnosc',
      heading: '11. Liability and availability',
      blocks: [
        {
          kind: 'p',
          text:
            'The Service is provided free of charge, in beta, “as is”. The Provider makes efforts to keep it ' +
            'working but does not guarantee uninterrupted availability or freedom from defects. Maintenance and ' +
            'outages may occur without prior notice.',
        },
        {
          kind: 'p',
          text:
            'The Provider is not liable for game content to the extent it originates from users or was generated by ' +
            'AI models, on the terms set out in Article 6 of the Digital Services Act. The Provider’s liability to ' +
            'users is limited to damage caused intentionally, to the extent permitted by law. Nothing here limits ' +
            'consumer rights arising from mandatory provisions of law.',
        },
        {
          kind: 'p',
          text:
            'The Provider reserves the right to end the closed beta, change the scope of services, or shut the ' +
            'Service down. Should the Service be shut down, it will give at least 30 days’ notice and allow content ' +
            'to be retrieved.',
        },
      ],
    },
    {
      id: 'rozwiazanie',
      heading: '12. Ending use and deleting your account',
      blocks: [
        {
          kind: 'p',
          text:
            'You may stop using the Service and schedule account deletion at any time in Account settings, or write to ' +
            `[${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}). Deletion follows a 14-day recovery period and is cancelled if ` +
            'you sign in again. The contract for electronic services ends when the account is deleted.',
        },
        {
          kind: 'p',
          text:
            'The Provider may terminate with 14 days’ notice, or with immediate effect in cases of gross breach of ' +
            'these Terms, stating the reason.',
        },
        {
          kind: 'p',
          text: 'What account deletion means for already-published games is described in the [Privacy Policy](/privacy).',
        },
      ],
    },
    {
      id: 'zmiany',
      heading: '13. Changes to these Terms',
      blocks: [
        {
          kind: 'p',
          text:
            'The Provider may change these Terms for good reason — changes in law, in the scope of services, or in ' +
            'how the Service works. We will announce changes in the Service and by email at least 14 days in ' +
            'advance. If you do not accept them, you may delete your account before they take effect.',
        },
      ],
    },
    {
      id: 'prawo',
      heading: '14. Governing law and disputes',
      blocks: [
        {
          kind: 'p',
          text:
            'Matters not covered by these Terms are governed by Polish law, in particular the Civil Code and the ' +
            'Act of 18 July 2002 on providing services by electronic means, together with directly applicable ' +
            'European Union law. The choice of Polish law does not deprive a consumer of the protection of ' +
            'mandatory provisions of the law of their habitual residence.',
        },
        {
          kind: 'p',
          text:
            'Consumers may use out-of-court dispute resolution, including the European Commission’s Online Dispute ' +
            'Resolution platform ([ec.europa.eu/consumers/odr](https://ec.europa.eu/consumers/odr)).',
        },
        {
          kind: 'p',
          text:
            'Personal data processing is described in the [Privacy Policy](/privacy), which forms an integral part ' +
            `of these Terms. The current version of these Terms is always available at ${SERVICE_URL}/terms.`,
        },
      ],
    },
  ],
};
