import { describe, expect, it } from 'vitest';
import { assembleGameHtml, MAX_PROJECT_BYTES, ProjectTooLargeError } from './assemble.js';

function project(overrides: Partial<Parameters<typeof assembleGameHtml>[0]> = {}) {
  return { title: 'Game', description: '', html: '<canvas></canvas>', js: 'const x = 1;', css: 'body{}', ...overrides };
}

describe('the size cap', () => {
  /**
   * The number that matters is not this one on its own — it is whether it still matches
   * `MAX_BUNDLE_BYTES` in the games repo's tools/validate.ts. A game that clears Check 4
   * gets merged and published, and then has to assemble here to be playable at all. When
   * the games repo raised its cap for the touch layer and this side was left behind,
   * block-cascade and rooftop-dash went live and answered 422.
   *
   * If this fails because the games repo moved, move this to match it — do not relax the
   * assertion.
   */
  it('matches the budget the games repo enforces in Check 4', () => {
    // Sourced from games-repo-contract.ts; CI re-checks the live games-repo
    // MAX_BUNDLE_BYTES when GAMES_REPO_TOKEN is set (issue #247). Website-first
    // budget raises update this number before games-repo main catches up.
    expect(MAX_PROJECT_BYTES).toBe(4_514_192);
  });

  it('accepts a game that fills the budget', () => {
    const filler = 'x'.repeat(MAX_PROJECT_BYTES - 100);
    expect(() => assembleGameHtml(project({ js: filler }))).not.toThrow();
  });

  it('rejects a game one byte over it', () => {
    const overBy = MAX_PROJECT_BYTES + 1 - '<canvas></canvas>'.length - 'body{}'.length;
    expect(() => assembleGameHtml(project({ js: 'x'.repeat(overBy) }))).toThrow(ProjectTooLargeError);
  });
});

/**
 * AI Act art. 50(2), applicable from 2 August 2026: output generated by an AI system
 * has to be marked as such in a machine-readable form. The marking has to travel with
 * the document — a badge drawn by the app around it is the visible half of the same
 * obligation, and is lost the moment the file is saved or embedded elsewhere.
 */
describe('AI provenance marking', () => {
  it('marks every assembled game as AI-generated, machine-readably', () => {
    const html = assembleGameHtml(project());
    expect(html).toContain('<meta name="ai-generated" content="true" />');
    expect(html).toContain('name="ai-provenance"');
  });

  it('marks network-restricted previews too', () => {
    const html = assembleGameHtml(project(), { restrictNetwork: true });
    expect(html).toContain('<meta name="ai-generated" content="true" />');
    // The CSP it shares a head with must survive alongside it.
    expect(html).toContain('Content-Security-Policy');
  });

  it('keeps the marking out of the size budget it would otherwise eat', () => {
    // The cap is charged against the author's own html+js+css, not our wrapper — so a
    // game that exactly fills the budget must not be pushed over it by this disclosure.
    const filler = 'x'.repeat(MAX_PROJECT_BYTES - '<canvas></canvas>'.length - 'body{}'.length);
    expect(() => assembleGameHtml(project({ js: filler }))).not.toThrow();
  });
});
