// get a random subset of fantasy city names collection
export function getRandomCityNames(count: number) {
  return [...CITY_NAMES]
    .sort(() => Math.random() - Math.random())
    .slice(0, count);
}

// Fantasy names for cities
export const CITY_NAMES = [
  "Elloria",
  "Velaris",
  "Cairndor",
  "Morthril",
  "Silverkeep",
  "Eaglebrook",
  "Frostholm",
  "Mournwind",
  "Shadowfen",
  "Sunspire",
  "Tristfall",
  "Winterhold",
  "Duskendale",
  "Ravenwood",
  "Greenguard",
  "Dragonfall",
  "Stormwatch",
  "Starhaven",
  "Ironforge",
  "Ironclad",
  "Goldshire",
  "Blacksand",
  "Ashenvale",
  "Whisperwind",
  "Brightwater",
  "Highrock",
  "Stonegate",
  "Thunderbluff",
  "Dunewatch",
  "Zephyrhills",
  "Fallbrook",
  "Lunarglade",
  "Stormpeak",
  "Cragmoor",
  "Ridgewood",
  "Mistvale",
  "Eversong",
  "Coldspring",
  "Hawke's Hollow",
  "Pinecrest",
  "Thornfield",
  "Emberfall",
  "Stormholm",
  "Myrkwater",
  "Windstead",
  "Feyberry",
  "Duskmire",
  "Elmshade",
  "Stonemire",
  "Willowdale",
  "Grimmreach",
  "Thundertop",
  "Nighthaven",
  "Sunfall",
  "Ashenwood",
  "Brightmire",
  "Stoneridge",
  "Ironoak",
  "Mithrintor",
  "Sablecross",
  "Westwatch",
  "Greendale",
  "Dragonspire",
  "Eagle's Perch",
  "Stormhaven",
  "Brightforge",
  "Silverglade",
  "Mournstone",
  "Opalspire",
  "Griffon's Roost",
  "Sunshadow",
  "Frostpeak",
  "Thorncrest",
  "Goldspire",
  "Darkhollow",
  "Eastgate",
  "Wolf's Den",
  "Shrouded Hollow",
  "Brambleshire",
  "Onyxbluff",
  "Skystone",
  "Cinderfall",
  "Emberstone",
  "Stormglen",
  "Highfell",
  "Silverbrook",
  "Elmsreach",
  "Lostbay",
  "Gloomshade",
  "Thundertree",
  "Bywater",
  "Nighthollow",
  "Firefly Glen",
  "Iceridge",
  "Greenmont",
  "Ashenshade",
  "Winterfort",
  "Duskhaven",
];
