// One route table shared by agent-channel.ts and mcp-server.ts.
export const AGENT_CHANNEL_ROUTES = {
  BRIEF: '/api/agent/build/brief',
  END: '/api/agent/build/end',
  EXAMPLES: '/api/agent/build/examples',
  EXAMPLES_BY_SLUG: '/api/agent/build/examples/:slug',
  EXAMPLES_BY_SLUG_FILE: '/api/agent/build/examples/:slug/file',
  EXAMPLES_BY_SLUG_FILES: '/api/agent/build/examples/:slug/files',
  GATE: '/api/agent/build/gate',
  INBOX: '/api/agent/build/inbox',
  INBOX_ACK: '/api/agent/build/inbox/ack',
  KIT: '/api/agent/build/kit',
  KIT_API: '/api/agent/build/kit/api',
  KIT_FILE: '/api/agent/build/kit/file',
  KIT_FILE_FRAGMENT: '/api/agent/build/kit/file/fragment',
  KIT_FILES: '/api/agent/build/kit/files',
  KIT_FILES_READ: '/api/agent/build/kit/files/read',
  KIT_SEARCH: '/api/agent/build/kit/search',
  KNOWLEDGE_QUERY: '/api/agent/build/knowledge/query',
  MEDIA: '/api/agent/build/media',
  PREVIEW: '/api/agent/build/preview',
  PROGRESS: '/api/agent/build/progress',
  REFERENCE_IMAGES: '/api/agent/build/reference-images',
  SEED: '/api/agent/build/seed',
  SEED_REGENERATE: '/api/agent/build/seed/regenerate',
  SHOT: '/api/agent/build/shot',
  SHOT_UPLOAD: '/api/agent/build/shot/upload',
  SHOT_UPLOAD_URL: '/api/agent/build/shot/upload-url',
  SOURCES: '/api/agent/build/sources',
  SOURCES_STAGE: '/api/agent/build/sources/stage',
  SOURCES_STAGE_CLEAR: '/api/agent/build/sources/stage/clear',
  SOURCES_STAGE_DELETE: '/api/agent/build/sources/stage/delete',
  SOURCES_STAGE_PATCH: '/api/agent/build/sources/stage/patch',
  SOURCES_STAGE_UPLOAD: '/api/agent/build/sources/stage/upload',
  TRANSCRIPT: '/api/agent/build/transcript',
} as const;

export type AgentChannelRouteKey = keyof typeof AGENT_CHANNEL_ROUTES;
export type AgentChannelRoutePath = (typeof AGENT_CHANNEL_ROUTES)[AgentChannelRouteKey];
