import type { GameProject } from '@gamedevpl/contract';
import { findCredentialLikeStrings } from './credential-scan.js';
import { MAX_PROJECT_BYTES as CONTRACT_MAX_PROJECT_BYTES } from './games-repo-contract.js';

/**
 * Combined html+js+css size cap. Sourced from `games-repo-contract.ts` so Check 4
 * in the games repo and this serve gate cannot drift independently (issue #247).
 */
export const MAX_PROJECT_BYTES = CONTRACT_MAX_PROJECT_BYTES;

export class ProjectTooLargeError extends Error {}
export class EmptyProjectError extends Error {}
export class CredentialLeakError extends Error {}

export interface AssembleOptions {
  /**
   * Inject a strict Content-Security-Policy meta so the game cannot reach the
   * network (no external scripts, images, fonts, or fetch/beacon). Games are
   * self-contained by construction, so this is a no-op for legitimate games but
   * closes the "phone home" gap when serving code that has not been reviewed yet
   * (e.g. an unmerged PR preview). Defaults to off.
   */
  restrictNetwork?: boolean;
}

// default-src 'none' denies everything, then we re-allow only inline script/style
// (the game's own code) and data: images (procedural sprites). No connect-src, so
// fetch/XHR/WebSocket/beacon are all blocked.
const RESTRICTIVE_CSP =
  "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; " +
  "img-src data:; font-src data:; media-src data:; base-uri 'none'; form-action 'none'";

/**
 * Machine-readable "this was made by an AI" marking, carried by the game document
 * itself (AI Act art. 50(2), applicable from 2 August 2026).
 *
 * It lives in the assembled document rather than in the app's UI on purpose: a
 * disclosure that only exists in the player is lost the moment the file is saved,
 * embedded, or scraped, and the obligation is to mark the *output*, not the page
 * that happens to show it. The visible half of the disclosure — badges and the
 * footer notice — is in apps/web; both halves are required, neither substitutes.
 */
const AI_PROVENANCE_META = [
  '    <meta name="ai-generated" content="true" />',
  '    <meta name="ai-provenance" content="Generated by an AI coding agent from a user-supplied game description." />',
  '    <meta name="generator" content="gamedev.pl" />',
].join('\n');

/**
 * Assembles a GameProject into one self-contained HTML document for iframe srcdoc.
 * The document runs in a sandboxed iframe (no allow-same-origin) on the client, so
 * we don't sanitize the code — isolation, not inspection, is the safety boundary.
 * We only enforce basic hygiene: non-empty markup/logic and a size cap.
 */
export function assembleGameHtml(project: GameProject, options: AssembleOptions = {}): string {
  if (!project.html.trim() || !project.js.trim()) {
    throw new EmptyProjectError('generated project is missing html or js');
  }

  const totalBytes = Buffer.byteLength(project.html + project.js + project.css, 'utf8');
  if (totalBytes > MAX_PROJECT_BYTES) {
    throw new ProjectTooLargeError(`generated project is ${totalBytes} bytes, over the ${MAX_PROJECT_BYTES} cap`);
  }

  const findings = findCredentialLikeStrings(project.html + project.js + project.css);
  if (findings.length > 0) {
    throw new CredentialLeakError('generated project contains credential-like strings');
  }

  const cspMeta = options.restrictNetwork
    ? `\n    <meta http-equiv="Content-Security-Policy" content="${RESTRICTIVE_CSP}" />`
    : '';

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />${cspMeta}
${AI_PROVENANCE_META}
    <title>${escapeHtml(project.title)}</title>
    <style>${project.css}</style>
  </head>
  <body>
${project.html}
    <script>${project.js}</script>
  </body>
</html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
