import type { GameProject } from '@gamedevpl/game-generator';
import { findCredentialLikeStrings } from './credential-scan.js';

/**
 * What a game may spend on itself. The games repo enforces the same budget in
 * `tools/validate.ts` (Check 4), and the two must agree: this cap decides whether a
 * game can be *served*, so anything CI accepts and merges has to assemble here, or the
 * game is published and unplayable.
 */
const GAME_BUDGET_BYTES = 200 * 1024;

/**
 * The GameKit touch layer — on-screen pad plus its shell CSS — is inlined into every
 * assembled game whether the game asked for it or not, and costs 7,501 bytes. The games
 * repo added exactly this allowance on top of the budget (`GAMEKIT_TOUCH_BYTES` in
 * tools/validate.ts) rather than charging a platform feature to each author.
 *
 * Keep the two numbers equal. When only the games repo was raised, block-cascade and
 * rooftop-dash passed CI, merged, and then 422'd on the play route, and a build sitting
 * at 208,001 bytes could not be previewed by the creator watching it being made.
 */
const GAMEKIT_TOUCH_BYTES = 7_501;

/** Combined html+js+css size cap. Generated code is served, not stored, so keep it modest. */
export const MAX_PROJECT_BYTES = GAME_BUDGET_BYTES + GAMEKIT_TOUCH_BYTES;

export class ProjectTooLargeError extends Error {}
export class EmptyProjectError extends Error {}
export class CredentialLeakError extends Error {}

export interface AssembleOptions {
  /**
   * Inject a strict Content-Security-Policy meta so the game cannot reach the
   * network (no external scripts, images, fonts, or fetch/beacon). Games are
   * self-contained by construction, so this is a no-op for legitimate games but
   * closes the "phone home" gap when serving code that has not been reviewed yet
   * (e.g. an unmerged PR preview). Defaults to off.
   */
  restrictNetwork?: boolean;
}

// default-src 'none' denies everything, then we re-allow only inline script/style
// (the game's own code) and data: images (procedural sprites). No connect-src, so
// fetch/XHR/WebSocket/beacon are all blocked.
const RESTRICTIVE_CSP =
  "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; " +
  "img-src data:; font-src data:; media-src data:; base-uri 'none'; form-action 'none'";

/**
 * Machine-readable "this was made by an AI" marking, carried by the game document
 * itself (AI Act art. 50(2), applicable from 2 August 2026).
 *
 * It lives in the assembled document rather than in the app's UI on purpose: a
 * disclosure that only exists in the player is lost the moment the file is saved,
 * embedded, or scraped, and the obligation is to mark the *output*, not the page
 * that happens to show it. The visible half of the disclosure — badges and the
 * footer notice — is in apps/web; both halves are required, neither substitutes.
 */
const AI_PROVENANCE_META = [
  '    <meta name="ai-generated" content="true" />',
  '    <meta name="ai-provenance" content="Generated by an AI coding agent from a user-supplied game description." />',
  '    <meta name="generator" content="gamedev.pl" />',
].join('\n');

/**
 * Assembles a GameProject into one self-contained HTML document for iframe srcdoc.
 * The document runs in a sandboxed iframe (no allow-same-origin) on the client, so
 * we don't sanitize the code — isolation, not inspection, is the safety boundary.
 * We only enforce basic hygiene: non-empty markup/logic and a size cap.
 */
export function assembleGameHtml(project: GameProject, options: AssembleOptions = {}): string {
  if (!project.html.trim() || !project.js.trim()) {
    throw new EmptyProjectError('generated project is missing html or js');
  }

  const totalBytes = Buffer.byteLength(project.html + project.js + project.css, 'utf8');
  if (totalBytes > MAX_PROJECT_BYTES) {
    throw new ProjectTooLargeError(`generated project is ${totalBytes} bytes, over the ${MAX_PROJECT_BYTES} cap`);
  }

  const findings = findCredentialLikeStrings(project.html + project.js + project.css);
  if (findings.length > 0) {
    throw new CredentialLeakError('generated project contains credential-like strings');
  }

  const cspMeta = options.restrictNetwork
    ? `\n    <meta http-equiv="Content-Security-Policy" content="${RESTRICTIVE_CSP}" />`
    : '';

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />${cspMeta}
${AI_PROVENANCE_META}
    <title>${escapeHtml(project.title)}</title>
    <style>${project.css}</style>
  </head>
  <body>
${project.html}
    <script>${project.js}</script>
  </body>
</html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
