export const PHONE_PAGE = String.raw`<!doctype html><html><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Play on phone</title>
<style>html,body{margin:0;background:#080c12;color:#fff;font:16px system-ui}iframe{position:fixed;inset:0;width:100%;height:100%;border:0}nav{position:fixed;top:10px;left:10px;right:10px;display:flex;gap:8px;flex-wrap:wrap;pointer-events:none}nav>*{pointer-events:auto}button,textarea{font:inherit;padding:10px;border-radius:8px}#status{background:#111c;padding:8px}dialog{background:#16202f;color:white;width:85%;border:0;border-radius:14px}textarea{width:90%}</style>
<iframe id="game" sandbox="allow-scripts allow-pointer-lock" title="Game"></iframe><nav><span id="status">Connecting…</span><button id="update">Load latest build</button><button id="report">Report a moment</button></nav>
<dialog id="sheet"><h2>Send feedback to computer</h2><p>Includes the shown build, screenshot and diagnostic trace when available.</p><textarea id="text" maxlength="8000"></textarea><p id="notice"></p><button id="send">Send</button><button id="close">Close</button></dialog>
<script>
const el=id=>document.getElementById(id),frame=el('game');let revision='',pending,capture;
const token=location.hash.slice(1)||sessionStorage.getItem('phone-token')||'';sessionStorage.setItem('phone-token',token);history.replaceState(null,'','/');
function uuid(){const a=crypto.getRandomValues(new Uint8Array(16));a[6]=a[6]&15|64;a[8]=a[8]&63|128;const h=[...a].map(x=>x.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);}
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(50000)});if(!r.ok)throw Error('Disconnected or access revoked ('+r.status+')');return r.json();}
async function load(){try{const b=await api('/game');frame.srcdoc=b.html;revision=b.revision;el('status').textContent='Playing '+revision.slice(0,10);}catch(e){el('status').textContent=e.message;}}
el('update').onclick=()=>{if(!revision||confirm('Load latest build and restart this phone game?'))void load();};
function collect(){return new Promise(resolve=>{const id=uuid(),result={revision};const listener=e=>{if(e.source!==frame.contentWindow)return;if(e.data?.source==='gdpl-player'&&e.data.type==='snapshot'&&e.data.reason==='capture'&&typeof e.data.png==='string'&&e.data.png.length<=2000000)result.png=e.data.png;if(e.data?.source==='gdpl-workbench-game'&&e.data.id===id){const raw=JSON.stringify(e.data.data);if(raw&&raw.length<=200000)result.diagnostics=raw;}};addEventListener('message',listener);frame.contentWindow.postMessage({source:'gdpl-host',type:'capture'},'*');frame.contentWindow.postMessage({source:'gdpl-workbench',type:'trace',id},'*');setTimeout(()=>{removeEventListener('message',listener);resolve(result);},700);});}
el('report').onclick=async()=>{capture=await collect();el('sheet').showModal();};el('close').onclick=()=>el('sheet').close();
el('send').onclick=async()=>{if(!el('text').value.trim())return;pending??={id:uuid(),text:el('text').value,...capture};el('send').disabled=true;try{await api('/report',pending);pending=undefined;el('notice').textContent='Sent to the computer. The editor decides when to send it to the agent.';el('text').value='';}catch(e){el('notice').textContent=e.message+' Retry retains the same report ID.';}finally{el('send').disabled=false;}};
async function tick(){try{const b=await api('/status');el('status').textContent='Playing '+revision.slice(0,10)+(b.revision!==revision?' · update ready':'');}catch(e){el('status').textContent=e.message;}setTimeout(tick,3000);}load();tick();
</script></html>`;
