#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy to Github pages

on:
  workflow_run:
    workflows: ['Lint and test']
    branches: [master]
    types:
      - completed

defaults:
  run:
    working-directory: ./website

jobs:
  deploy_pages:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
      - run: npm install --prefix=../games/monster-steps
      - run: npm install --prefix=../games/nukes
      - run: npm install --prefix=../games/masterplan
      - run: npm install --prefix=../games/xmas
      - run: npm install --prefix=../games/hungry-lion
      - run: npm install --prefix=../games/tribe
      - run: npm install
      - run: npm run build --prefix=../games/monster-steps
      - run: npm run build --prefix=../games/nukes
      - run: npm run build --prefix=../games/masterplan
      - run: npm run build --prefix=../games/xmas
      - run: npm run build --prefix=../games/hungry-lion
      - run: npm run build --prefix=../games/tribe
      - run: npm run build
      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: website/build # The folder the action should deploy.
